services:
  - type: web
    name: futbol-api
    env: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: DATABASE_URL
        fromDatabase:
          name: futbol-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: futbol-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: futbol-db
          property: password
      - key: DATABASE_DRIVER
        value: org.postgresql.Driver
      - key: DDL_AUTO
        value: update

databases:
  - name: futbol-db
    plan: free
    databaseName: futboldb
    user: futboluser

